### ISSUE TITLE
View de confirmação do email

### ISSUE THREAD

**Issue by dudustefanello** [dudustefanello/pgpgerenciador#10]
**Tempo estimado:** 01:10
**Tempo de desenvolvimento:** 00:23

**Comment by renanbabinski** [comment]
code review por Renan Babinski
Em 01/12/2020
Tempo: 00:05

**Comment by renanbabinski** [comment]
Testado por Renan Babinski
Em 01/12/2020
Tempo: 00:05

OBS: logar o usuário na confirmação

**Comment by renanbabinski** [comment]
Testado por Renan Babinski
Em 01/12/2020
Tempo: 00:01
