### ISSUE TITLE
Alteração do template de inclusão de link para incluir botão

### ISSUE THREAD

**Issue by eassisv** [dudustefanello/pgpgerenciador#21]
**Tempo estimado:** 00:15

**Comment by dudustefanello** [comment]
Desenvolvido por **Eduardo Stefanello**
Em **24/11/2020**
Tempo gasto: **00:10**

**Comment by renanbabinski** [comment]
code review por Everton
Em 30/11/2020
Tempo: 00:01

**Comment by renanbabinski** [comment]
testado por Renan Babinski
Em 01/12/2020
Tempo: 00:05
