### ISSUE TITLE
Template de cadastro de usuario

### ISSUE THREAD

**Issue by eassisv** [dudustefanello/pgpgerenciador#23]
**Tempo estimado:** 01:00

**Comment by renanbabinski** [comment]
Desenvolvido por Renan Babinski
Em 30/11/2020
Tempo gasto: 00:40

**Comment by dudustefanello** [comment]
Code Review por Eduardo Stefanello
Em 30/11/2020
Tempo gasto: 00:15

**Comment by dudustefanello** [comment]
Teste por Eduardo Stefanello
Em 30/11/2020
Tempo gasto: 00:20
