### ISSUE TITLE
Template do email que será enviado

### ISSUE THREAD

**Issue by eassisv** [dudustefanello/pgpgerenciador#25]
**Tempo estimado:** 01:30
**Tempo de desenvolvimento:** 00:40

**Comment by dudustefanello** [comment]
Code review por Eduardo Stefanello em 14/12/2020
Tempo gasto: 00:10

**Comment by dudustefanello** [comment]
Testado por Eduardo Stefanello em 15/12/2020
Tempo gasto: 00:10
