### ISSUE TITLE
Template de lista

### ISSUE THREAD

**Issue by eassisv** [dudustefanello/pgpgerenciador#26]
**Tempo estimado:** 01:00
**Tempo de code review:** 00:01
**Tempo de teste:** 00:03

O link salvo está apontando para o Medium e não para a aplicação

**Comment by dudustefanello** [comment]
Desenvolvido por **Eduardo Stefanello**
Em **24/11/2020**
Tempo gasto: **00:30**

**Comment by dudustefanello** [comment]
Desenvolvido e testado por Eduardo Stefanello em 14/12/2020
Tempo gasto: 00:20
