### ISSUE TITLE
Template do formulário para inserir o link

### ISSUE THREAD

**Issue by dudustefanello** [dudustefanello/pgpgerenciador#4]
**Tempo estimado:** 01:00

Criação do template com único campo e botão de submmit com o [AMANDA_TEMPLATE](https://github.com/dudustefanello/pgpgerenciador/blob/master/AMANDA-TEMPLATE.zip)

**Comment by renanbabinski** [comment]
Code Review por Renan Babinski
Em 20/10/2020 às 22:33
Tempo de review: 0:10

**Comment by renanbabinski** [comment]
Testado por Renan Babinski
Em 26/10/2020
Tempo de Testes: 00:10

* Nenhum problema identificado no template
