### ISSUE TITLE
Criação da view de inclusão de link

### ISSUE THREAD

**Issue by dudustefanello** [dudustefanello/pgpgerenciador#5]
**Tempo estimado:** 01:30

* Criar a view para utilizar o template do #4;
* Classe de Form;
* Validar o link (#3) no método POST;
* Passar o *link* por GET para a view do texto formatado.

**Comment by dudustefanello** [comment]
Desenvolvido por Eduardo Stefanello
Em 19/10/2020
Tempo de desenvolvimento: 1:15

**Comment by eassisv** [comment]
Code Review por Éverton Assis
Em 19/10/2020 às 21:47
Tempo de review: 0:10

**Comment by renanbabinski** [comment]
Teste por Renan Babinski
Em 26/10/2020
Tempo de teste : 10 minutos

1- Problemas identificados:

* Quando um post é elaborado por um usuário o nickname dele é incluído no inicio da URL [medium.com](medium.com). **A URL não passa na validação**
    - Exemplo de link com usuário : [https://forge.medium.com/youre-not-bad-at-time-management-you-re-doing-too-much-10fbeb8c5f5d](https://forge.medium.com/youre-not-bad-at-time-management-you-re-doing-too-much-10fbeb8c5f5d)
    - Nesse caso, acessando [forge.medium.com](forge.medium.com) você tem acesso ao perfil do usuário

**Comment by dudustefanello** [comment]
Corrigido por Eduardo Stefanello
Em 27/10/2020
Tempo gasto: 00:10

**Comment by renanbabinski** [comment]
Testado por Renan Babinski
Em 27/10/2020 as 22:16
Tempo de teste: 00:10
