### ISSUE TITLE
Template para mostrar o texto

### ISSUE THREAD

**Issue by dudustefanello** [dudustefanello/pgpgerenciador#6]
**Tempo estimado:** 01:20

Criação do template para artigo usando [AMANDA_TEMPLATE](https://github.com/dudustefanello/pgpgerenciador/blob/master/AMANDA-TEMPLATE.zip)

**Comment by renanbabinski** [comment]
Code review por Renan Babinski
Em 27/10/2020 as 21:33
Tempo de Review: 00:10

**Comment by renanbabinski** [comment]
Testado por Renan Babinski
Em 27/10/2020 as 21:52
Tempo de Teste 00:10

**Comment by dudustefanello** [comment]
Desenvolvido por Eduardo Stefanello
Em 27/10/2020
Tempo gasto: 00:20
