### ISSUE TITLE
Criação da view do texto

### ISSUE THREAD

**Issue by dudustefanello** [dudustefanello/pgpgerenciador#7]
**Tempo estimado:** 01:00

* Criar a view para utilizar o template do #6;
* Utilizar o link validado para fazer a requisição;
* Extrair (#2) o texto e apresentar com formatação padronizada.

**Comment by dudustefanello** [comment]
Code Review por Eduardo Stefanello
Em 20/10/2020
Tempo gasto: 00:15

Problema identificado na view:

* Precisa ser uma classe de view, herança de TemplateView
* Precisa definir uma variável de contexto para retornar o texto. Pode ser feito implementando um update no resultado do método `get_context_data`
* Precisa utilizar o valor que vem por parâmetro GET;

**Comment by renanbabinski** [comment]
Desenvolvido por Renan Babinski
Em 20/10/2020
Tempo de desenvolvimento: 0:15

**Comment by renanbabinski** [comment]
Desenvolvido por Renan Babinski
Em 26/10/2020
Tempo de desenvolvimento: 0:30

Correção e implementação das funções requeridas

* Agora um link válido direciona para a página "text"
* Herdei o template base só pra ficar mais bonito, mas será alterado
* A View do texto pega o link que vem por GET e mostra, assim como o texto que vem da View é mostrado no HTML pela váriavel de contexto

**Comment by dudustefanello** [comment]
Code Review por Eduardo Stefanello
Em 26/10/2020
Tempo gasto: 00:05

**Comment by dudustefanello** [comment]
Testado por Eduardo Stefanello
Em 26/10/2020
Tempo gasto: 00:10
