### ISSUE TITLE
Template de login

### ISSUE THREAD

**Issue by dudustefanello** [dudustefanello/pgpgerenciador#8]
**Tempo estimado:** 01:00

**Comment by dudustefanello** [comment]
Desenvolvido por **Eduardo Stefanello**
Em **24/11/2020**
Tempo gasto: **00:40**

**Comment by renanbabinski** [comment]
Code review por Renan Babinski
Em 30/11/2020
Tempo gasto: 00:10

**Comment by renanbabinski** [comment]
Testado por Renan Babinski
Em 30/11/2020
Tempo Gasto: 00:05
